### ISSUE TITLE
pre-build step?

### ISSUE THREAD

**Issue by paleozogt** [avirshup/DockerMake#42]
Currently, `build` runs after all the `requires` run.  Could we have a `pre_build` that runs *before* the `requires`?  ie,

```
foobar:
    FROM: foobase
    pre_build: |
       RUN do stuff before foo and bar run
    requires:
       - foo
       - bar
    build: |
       RUN do stuff after foo and bar run

foo:
    build: |
       RUN do foo stuff

bar:
    build: |
       RUN do bar stuff
```
