### ISSUE TITLE
Build-time secrets: features and/or best practices with DockerMake (decision)

### ISSUE THREAD

**Issue by avirshup** [avirshup/DockerMake#53]
Implement (or just document, if already possible) a reasonable method for passing build-time secrets that aren't accessible after build-time. See also https://runnable.com/docker/rails/managing-secrets-during-docker-builds

E.g., a build where we install artifacts from internal enterprise github, which requires a token for auth.

Options:
 1. Pass one-time-use tokens to docker-make (e.g., with hashicorp vaults)
   Pro: already supported
   Cons: cache becomes very difficult to reason about; potentially painful to set up; build-args feel brittle

 2. Auto-squashing
  Pro: easy to reason about
  Cons: no caching, no shared layers

 3. Context set-up - download artifacts into build context before the build
  Pro: pretty easy to reason about; pretty easy to implement
  Con: lose the reproducibility of the docker builds; build context becomes brittle

4. Multi-stage builds
  Pro: keeps the build docker-based
  Con: somewhat tricky to set up; caching will also cache the secrets; pushing build images accidentally will publish secrets

Let's say the right solution will need to have the following properties:

1. Maintains layers - when pushed to a registry, images can still share layers.
2. Caching as normal for normal build steps - even if a "normal" depends on something that came from "secrets" layer, caching should work normally
3. Protection against sharing secrets

**Comment by avirshup** [comment]
Proposal: multi-stage builds with explicit secret protection

Let's say you define a stage that involves secrets like so:
```yml
secret-stage:
   secret-args-file: [path to file]  # we don't want to even tempt people into defining these here
   [all other keys are as normal]
```
This stage _cannot_ be a target; docker-make will refuse to build it or anything that `requires` it.

Instead, secret-containing images can only be accessed via the `copy_from` directive; essentially, these give you extra, docker-based "context" for your builds.

So, the only additional docker-make needs here would be to
  - read a secret-arg-file,
  - not allow any secret-arg-file-containing layers to end up in a target

In this case:
Cache layers for the secret layers _would_ remain accessible on the build machine. But docker-make will never tag them with anything, thus making it nearly impossible to inadvertently push them.

**Comment by avirshup** [comment]
Given the above, here's what that would look like

DockerMake.yml:
```yml
pull-artifacts:  # this is secret! It can't be a build target
   FROM: python:3.6-slim
   secret-args-file: .secrets.env
   build: |
      WORKDIR /opt/sources
      ARG PYPIUSER PYPIPASSWORD
      RUN pip download --repository-url \
            https://${PYPIUSER}:${PYPIPASSWORD}@pypi.internal/simple \
            package1==1.1.1 \
            package2==2.2.2

install-artifacts:
    FROM: python:3.6-slim
    copy_from:
        pull-artifacts:
            /opt/sources: /opt/sources
```

Actually, this kind of sucks; you can't install directly from the server (or if you do, then you need to copy the installation between images, which sucks even more).

**Comment by avirshup** [comment]
What about selective squashing, in which we only squash enough layers to destroy the build arguments? This appears to be possible: https://github.com/goldmann/docker-squash

If possible, this would let us install directly from the server. Docker caching not be available at any squashed layer. However, IF it's acceptable to keep the intermediate, secret-containing layers around (and to me, it is), then we can just map the squashed to unsquashed versions in our chain of intermediate images*

```yml
install-artifacts:
   FROM: python:3.6-slim
   secret-args-file: .secrets.env
   build: |
      WORKDIR /opt/sources
      ARG PYPIUSER PYPIPASSWORD
      RUN pip install --repository-url \
            https://${PYPIUSER}:${PYPIPASSWORD}@pypi.internal/simple \
            package1==1.1.1 \
            package2==2.2.2

next-step:
   requires:
      - install-artifacts
   [...]
```

In this instance, docker-make (possibly using `docker-squash`) would automatically squash and rename the install-artifacts layer when it's done building. It would be a perfectly valid build target.

Definitely easy to understand here, since you just need to add secrets to a step and everything else is taken care of. We'd need to add in the new caching pretty quickly.

*i.e., the first time a build is run, let's say the _unsquashed_ version of `install-artifacts` has image ID `AAA`, and the version with a _squashed_ top layer has image ID `BBB`. In thise case, `next-steps will be built on top of `BBB`. On further builds, if building `install-artifacts` continue to yield `AAA`, `next-steps` will continue to be built on `BBB`.
